name: Buy lotto Sub
on:
  schedule:
    - cron: 33 0 * * 1 # every Monday on 09:33 AM (KST)
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    name: Buy lotto Sub
    steps:  

      - uses: actions/checkout@v3    
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      
      - name: Run Scripts
        run: make buy
        env:
          USERNAME: ${{ secrets.USERNAME_SUB }}
          PASSWORD: ${{ secrets.PASSWORD_SUB }}
          COUNT: ${{ secrets.COUNT }}
          LOTTO_STRATEGY: SUPERSTITION  # AUTO 또는 SUPERSTITION
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          DISCORD_WEBHOOK_URL:  ${{ secrets.DISCORD_WEBHOOK_URL }}
